//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr30.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи_
    {
        public double id { get; set; }
        public string фио { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<double> id_role { get; set; }
    }
}
