//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr30.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункт_выдачи
    {
        public double id { get; set; }
        public Nullable<double> Индекс { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public Nullable<double> Дом { get; set; }
    }
}
